.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GUGEL" "1" "July 2014" "" ""
.
.SH "NAME"
\fBgugel\fR \- convert pizza & Mountain Dew into rock\-solid (web) apps
.
.SH "DESCRIPTION"
\fBAlexander Gugel\fR turns pizza & Mountain Dew into rock\-solid web apps\. He is a brilliant Full\-Stack Software Engineer\. Currently, he is working on awesome projects @HackReactor \fIhttp://www\.hackreactor\.com/\fR\.
.
.P
In its default mode, \fBAlexander Gugel\fR converts one or more input \fIMountian Dew\fRs to awesome pieces of Software\. His productivity is awesome, but can be further enhanced through \fIIndian food\fR or \fIPizza\fR\. The \fB\-\-Node\.JS\fR, \fB\-\-Angular\.JS\fR, and \fB\-\-Backbone\.JS\fR options dictate which output files are generated\. A wide range of possible output files are available\.
.
.SH "PROJECTS"
.
.IP "\(bu" 4
\fBFastPass Exchange\fR \fIhttps://github\.com/fastpassexchange/fastpass\fR (Group project), \fITech Lead\fR
.
.IP
FastPass Exchange gives Disneyland visitors the power to go on all the rides they want, when they want\.
.
.IP "\(bu" 4
dove into existing code base and became fluent in Ionic within four days
.
.IP "\(bu" 4
fixed multiple bugs and enhanced Firebase integration using AngularFire
.
.IP "\(bu" 4
significantly enhanced UI and UX
.
.IP "" 0

.
.IP "\(bu" 4
\fBTrrnts\fR \fIhttps://github\.com/Trrnts/Trrnts\fR (Group Project), \fIProduct Owner, Tech Lead\fR
.
.IP
Trrnts is the front page for the BitTorrent network, providing insights through interactive analytics and data visualizations that leverage the DHT protocol\.
.
.IP "\(bu" 4
lead a team of developers as a tech lead and product owner
.
.IP "\(bu" 4
optimized, refactored and deployed existing code base while re implementing mission\-critical parts
.
.IP "\(bu" 4
enhanced existing D3 data visualisations by writing appropriate AngularJS directive
.
.IP "\(bu" 4
used advanced data\-structures, including HyperLogLog and Sorted Set in conjunction with Redis to achieve near real\-time monitoring while writing memory\-efficient code inspired by functional programming style scraped popular BitTorrent torrenting sites in order to bootstrap web app
.
.IP "" 0

.
.IP "\(bu" 4
\fBTrrnts\fR \fIhttps://github\.com/alexanderGugel/trrnts\-hackathon\fR (Hackathon Project)
.
.IP
Trrnts originally was a Proof of Concept that demonstrated the crawlability of the Mainline BitTorrent DHT network in order to monitor the popularity of pre\-defined torrents and local distribution of peers\.
.
.IP "\(bu" 4
implemented MVP within two days during Hackathon
.
.IP "\(bu" 4
designed, implemented and optimized a crawler for the Mainline BitTorrent DHT network
.
.IP "\(bu" 4
leveraged UDP based protocol and Node\.JS dgram library in order to monitor the popularity of various torrents
.
.IP "\(bu" 4
crawled about 12 mio peers and executed 10 thousand concurrent operations per second
.
.IP "\(bu" 4
organized and led team to continue working on the prototype
.
.IP "" 0

.
.IP "\(bu" 4
\fBOdin\fR \fIhttps://github\.com/alexanderGugel/Odin\fR (Learning Experience)
.
.IP
Odin is a foolproof text\-based multi\-room chat application inspired by the popular IRC protocol\.
.
.IP "\(bu" 4
leveraged Socket\.IO for real\-time updates
.
.IP "\(bu" 4
had ~30 users at peak
.
.IP "\(bu" 4
posted on Hacker News
.
.IP "" 0

.
.IP "\(bu" 4
\fBPenetration Testing\fR (Learning Experience)
.
.IP
Found security flaws in two major banking websites\.
.
.IP "\(bu" 4
analyzed banking websites for security vulnerabilities
.
.IP "\(bu" 4
accidentally discovered XSS open redirect vulnerabilities
.
.IP "" 0

.
.IP "\(bu" 4
\fBMeatr\fR (Learning Experience)
.
.IP
Meatr is a social network for German students\.
.
.IP "\(bu" 4
implemented social network while learning PHP
.
.IP "\(bu" 4
gained initial traction
.
.IP "\(bu" 4
had about 30 active users at peak
.
.IP "" 0

.
.IP "" 0
.
.P
Please note: The projects are sorted in reverse chronological order\. They do not necessarily reflect my badassery, but rather my personal and professional development\.
.
.SH "SKILLS"
.
.IP "\(bu" 4
\fBStrong\fR: Backbone\.JS, JavaScript, Node\.JS, Redis, Express, Socket\.IO, SQL, CoffeeScript, CSS, TDD, Git, Grunt, Gulp, Azure
.
.IP "\(bu" 4
\fBKnowledgable\fR: D3\.js, Ionic, MongoDB, Ruby, Sinatra, Java, AngularJS, MongoDB, Connect
.
.IP "\(bu" 4
\fBBasic\fR: Cordova, PHP, LevelDB, MQL4, Lisp, RethinkDB, PostgreSQL, Penetration Testing
.
.IP "" 0
.
.SH "BUGS"
\fBAlexander Gugel\fR is written in Node\.JS and depends on \fIpizza\fR and \fIMountain Dew\fR, extension libraries that are non\-trivial to install on some systems\. A more portable version of these dependencies would be welcome\.
.
.SH "COPYRIGHT"
gugel is Copyright (C) 2014 Alexander Gugel \fIalexander\.gugel@gmail\.com\fR
.
.SH "SEE ALSO"
GitHub \fIhttps://github\.com/alexanderGugel\fR LinkedIn \fIhttps://www\.linkedin\.com/in/alexandergugel\fR Twitter \fIhttps://twitter\.com/alexanderGugel\fR Svbtle \fIhttp://alexandergugel\.svbtle\.com/\fR Facebook \fIhttps://www\.facebook\.com/agugel\fR \fIalexander\.gugel@gmail\.com\fR
